### ISSUE TITLE
Segfault when using boost version 1.61

### ISSUE THREAD

**Issue by churli** [lhilbert/active-microemulsion#25]
If we build with boost 1.61, the `active-microemulsion` binary crashes when checking if the output folder exists.
From the core dump we get the following backtrace:
```
Program terminated with signal 11, Segmentation fault.
#0  0x000000000044a7bd in boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*) ()
(gdb) bt
#0  0x000000000044a7bd in boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*) ()
#1  0x0000000000403b59 in exists (p=...) at /usr/include/boost/filesystem/operations.hpp:289
#2  main (argc=1, argv=0x0) at /home/kit/itg/ct9558/Tmp/active-microemulsion/src/main.cpp:263
```

So we have a segfault originating from within boost::filesystem.

If we build with boost 1.56 then the binary runs fine.

**Comment by lhilbert** [comment]
This is not a problem when building and running locally on Mac.
